app:
  message:
  a: x
  b: x
  c: x
  d: x
  e: x
  f: x
  g: x
  h: x

langu:
  message:
  a: x
  b: x
  c: x
  d: x
  e: x
  f: x
  g: x
  h: x
  i: x
  j: x
  k: x
  l: x

carrier:
  message:
  a: x
  b: x
  c: x
  d: x
  e: x
  f: x
  g: x
  h: x
  i: x
  j: x
  k: x
  l: x
  m: x
  n: x
  o: x
  p: x
  q: x
  r: x
  s: x
  t: x
  u: x
  v: x
  w: x
  x: x
