server.port=9091
server.tomcat.uri-encoding=utf-8
spring.datasource.url=jdbc:mysql://119.23.188.166:3306/noman?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
spring.datasource.username=admin
spring.datasource.password=babt2017
#spring.datasource.url=jdbc:mysql://10.69.53.25:3306/noman?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
#spring.datasource.username=root
#spring.datasource.password=PB01@123.com
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.max-idle=10
#spring.datasource.max-wait=10000
#spring.datasource.min-idle=5
#spring.datasource.initial-size=5

spring.datasource.hikari.pool-name=SwitcherAppHikariPool1
spring.datasource.hikari.read-only=false
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.idle-timeout=60000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.login-timeout=5
spring.datasource.hikari.leak-detection-threshold=300


mybatis-plus.mapper-locations=classpath*:/mapper/**/**Mapper.xml
mybatis-plus.configuration.map-underscore-to-camel-case=true
#mybatis-plus.configuration.cache-enabled=true

spring.servlet.multipart.max-file-size=100MB

